### ISSUE TITLE
Disable support early closing of cdata sections

### ISSUE THREAD

**Issue by garg23neha** [HtmlUnit/htmlunit-neko#102]
This [PR](https://github.com/HtmlUnit/htmlunit-neko/commit/49a31c089482088aca57facb20e1a15792cfc3bd) is a blocker for us to use the latest version of htmlunit-neko since it's breaking a lot of tests of us.

Can you please disable this feature or suggest some ways to disable it.

**Comment by rbri** [comment]
@garg23neha this change was part of many fixes we did to bring the parser in sync with the spec.
And because the parser is used eg. by antisamy (https://github.com/OWASP/www-project-antisamy) i see no real reason to not follow the spec as good as possible (and browsers are interpreting the stuff the same way).

You can also have a look at this paper describing some of the negative effects of the parser incompatibilites https://www.ias.cs.tu-bs.de/publications/parsing_differentials.pdf

Or to make the story short - you are really sure that your expectations in the test are correct?

**Comment by rbri** [comment]
@garg23neha any news on this?

**Comment by rbri** [comment]
@garg23neha no response - will close this. Please open a new one if you need more support.
