### ISSUE TITLE
Update fix in an Specific version of nekohtml

### ISSUE THREAD

**Issue by LogeswaranRamasamy** [HtmlUnit/htmlunit-neko#123]
@rbri Is it possible to solve the below issue in the Older version of htmlunit-neko jar specifically in the neko-htmlunit-3.11.2.jar. 

[https://github.com/HtmlUnit/htmlunit-neko/issues/119](https://github.com/HtmlUnit/htmlunit-neko/issues/119) 

One of our production team is using this specific versions hence we need this fix in this specific version for the time being until they adapt the latest version. Is it possible??

**Comment by rbri** [comment]
@LogeswaranRamasamy technically it is possible but...

1. 3.11.2 has a severe bug regarding buffer handling. This was fixed in 3.11.3
2. there are two more major bugs that are also fixed in 3.11.3

see https://github.com/HtmlUnit/htmlunit-neko/compare/3.11.2...3.11.3 for all the changes

Therefore i like to suggest to build a version 3.11.4 that is based on 3.11.3 and has the fix for #119 on top

Or do you need a patched jar file with only the fix applied?

**Comment by rbri** [comment]
@LogeswaranRamasamy doing this work on old version is from my point of view a support activity for a company. Therefore i like to ask to pay for this work by sponsoring (https://github.com/sponsors/rbri). I think that is fair....

**Comment by LogeswaranRamasamy** [comment]
@rbri Able to get your point thanks a lot for the swift reply, will check on what can be done.

**Comment by rbri** [comment]
@LogeswaranRamasamy any news?

**Comment by rbri** [comment]
no response for a long time - will close this now; please open a new one if you still like to have something changed
