### ISSUE TITLE
Support for missing method in xerces

### ISSUE THREAD

**Issue by garg23neha** [HtmlUnit/htmlunit-neko#88]
@rbri In one of my company project, we are using getNonNormalizedValue() method from Xerces. But in the new implementation htmlunit-neko , this method is not present in [XMLAttributesImpl.java](https://github.com/HtmlUnit/htmlunit-neko/blob/master/src/main/java/org/htmlunit/cyberneko/xerces/util/XMLAttributesImpl.java).

Can you help me in understanding is there any alternate way for supporting getNonNormalizedValue() method?

**Comment by rbri** [comment]
@garg23neha  will have a look...

can you please explain the use case a bit more

**Comment by garg23neha** [comment]
@rbri we are using it in a function where we want Xerces to not resolve entities when it parses attributes

**Comment by rbri** [comment]
> we are using it in a function where we want Xerces to not resolve entities when it parses attributes

Ok, the getNonNormalizedValue() and most of the implementation was removed, because i have stripped neko down to the needs of HtmlUnit (and some other projects i'm aware of). And during the many performance optimizations we have removed nearly the whole support for this feature.

Have to think about a bit more....

**Comment by rbri** [comment]
@garg23neha do you need both versions of the attribute value or only the one one without the enriries resolved?
And what do you do with the enresolvrd entities from the attributes?

**Comment by garg23neha** [comment]
We need both version of attribute value i.e getValue(int) and getNonNormalizedValue(int) both are needed.
we don't resolve entities (&nbsp; and so on) while printing attribute values. Is there a different way to disable this in neko-htmlunit now?
We have a writer on top to exists to ensure we preserve CDATA blocks, without replacing them with entity escape sequences instead (simply because the resulting output for a code block is much nicer, and a little shorter, not for any other reason). Is there a way to enable this in neko-htmlunit now?

**Comment by garg23neha** [comment]
@rbri any inputs would be highly appreciated.

**Comment by rbri** [comment]
@rschwietzke what do you think about this - any idea how to do this without making the monster again slower?

**Comment by rschwietzke** [comment]
Depends on how we store that. If we have a second map for that, we certainly create more overhead again (at least 4 bytes per node without the map itself) which comes in at between about 24 to 100 bytes at least. How about making that an optional feature so that we can either use impl A or B of the attribute?

**Comment by garg23neha** [comment]
@rbri Are there any plans to bring it back?

**Comment by sumollodha** [comment]
+1 we also do use getNonNormalizedValue in our source code.

**Comment by garg23neha** [comment]
@rbri are there any plans on getting getNonNormalizedValue back to the code

**Comment by rbri** [comment]
will try

**Comment by rbri** [comment]
@garg23neha @sumollodha how should the getNonNormalizedValue() behave if the http://cyberneko.org/html/features/scanner/normalize-attrs is enabled?

in the old version it looks like the blanks are also removed from the getNonNormalizedValues method - but from the name it makes no sesnse for me.

**Comment by garg23neha** [comment]
@rbri I am not sure because we are not using the feature http://cyberneko.org/html/features/scanner/normalize-attrs

**Comment by rbri** [comment]
@garg23neha, @sumollodha the features is now really back please test with the 4.0.0-SNAPSHOT build and enable the 

    public static final String PLAIN_ATTRIBUTE_VALUES = "http://cyberneko.org/html/features/scanner/plain-attr-values";

feature.
I also added some chars to the readme - please have a look and provide feedback.

**Comment by garg23neha** [comment]
@rbri HTMLScannerTest.reader() test is failing for me.

**Comment by garg23neha** [comment]
@rbri do you know any case where getValue and getNonNormalizedValue can return different result?
In my project, we are using getNonNormalizedValue. So our use-case is when we get urls like http://www.example.org?name=bob&hat=bowler, the & will get get replaced otheriwse SAX parser will thing that &hat is a malformed entity definition. But getValue and getNonNormalizedValue are returning same result for "http://www.example.org?name=bob&hat=bowler". So I am not sure when can we see difference in the output of these two methods. Any pointers would be highly appreciated.

**Comment by rbri** [comment]
> @rbri HTMLScannerTest.reader() test is failing for me.

Why not adding any hints about the failure you get - do you really think i can guess that.....

**Comment by garg23neha** [comment]
> > @rbri HTMLScannerTest.reader() test is failing for me.
> 
> Why not adding any hints about the failure you get - do you really think i can guess that.....

[ERROR]   HTMLScannerTest.reader:340 expected: <(html
(head
)head
(body
(script
Atype text/javascript
"// 
)script
)body
)html> but was: <(html
(head
)head
(body
(script
Atype text/javascript
"// 
)script
)body
)html>

**Comment by garg23neha** [comment]
> > @rbri do you know any case where getValue and getNonNormalizedValue can return different result?
> 
> Yes of course, you have to
> 
> * enable the feature PLAIN_ATTRIBUTE_VALUES (see above) and
> * place an valid entity reference in one of the attributes
> 
> Or you have a look at the testcases i have added as part of this....
@rbri In the previous version of neko-html when we had the support for NonNormalizedValue then also do we need to enable any feature?

**Comment by rbri** [comment]
@garg23neha test is fixed, thanks

> In the previous version of neko-html when we had the support for NonNormalizedValue then also do we need to enable any feature?
I guess not - but for the current version we need this feature. The reason behind is simply performance and memory consumption. We spend a lot of time to optimize the parsing process to be faster and more memory friendly because some projects using this require this kind of optimization. Still not sure if adding the function back for you kills this other efforts in some way.

**Comment by rbri** [comment]
@sumollodha @garg23neha

because i lost the thread a bit i close this.

Please
* try the latest SNAPSHOT build (4.0.0-SNAPSHOT)
* check out the https://github.com/HtmlUnit/htmlunit-neko/blob/master/README.md#porting-from-3x-to-4x section for more info about the breaking change
* open new issues if still something is missing
